services:
  nexusdude-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexusdude-web
    restart: unless-stopped
    ports:
      - "8085:8000"
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    env_file:
      - .env
    networks:
      - monitoreo_default
      - netbox-docker_default

networks:
  monitoreo_default:
    external: true
  netbox-docker_default:
    external: true
